# Generated by Django 2.2.15 on 2020-08-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20200810_1331'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mystock',
            unique_together={('account', 'stock')},
        ),
    ]
